name: carcat
description: "Simplified auto service mobile application."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+3

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.3
  flutter_svg: ^2.1.0
  flutter_bloc: ^9.1.1
  flutter_hooks: ^0.21.3+1
  pinput: ^5.0.2
  dio: ^5.9.0
  awesome_dio_interceptor: ^1.3.0
  hive_flutter: ^1.1.0
  get_it: ^9.2.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  fluttertoast: ^9.0.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  dotted_border: ^3.1.0
  lottie: ^3.3.1
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  font_awesome_flutter: ^10.12.0
  pretty_dio_logger: ^1.4.0
  permission_handler: ^12.0.1
  image: ^4.5.4
  google_mlkit_text_recognition: ^0.15.1
  google_fonts: ^6.3.3
  crypto: ^3.0.7
  flutter_secure_storage: ^10.0.0
  http_parser: ^4.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/png/carcat_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/
    - assets/lottie/

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
